version: "3"
services:
  app:
    container_name: cake-pals-app
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    container_name: cake-pals-db
    image: mongo
    restart: always
    volumes:
      - ./db-data:/data/db
    expose:
      - 27017
    ports:
      - 27019:27017